[package]
name = "winston"
version = "0.1.1"
edition = "2021"
description = "winston for rust"
license = "MIT"
documentation = "https://docs.rs/winston"
repository = "https://github.com/ifeanyi-ugwu/winston_rs"
authors = ["ifeanyi ugwu"]
keywords = ["winston", "logger"]
categories = ["development-tools::debugging"]


[dependencies]
chrono = "0.4.38"
logform = "0.1.3"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
