[package]
name = "winston"
version = "0.1.2"
edition = "2021"
description = "winston for rust"
license = "MIT"
documentation = "https://docs.rs/winston"
repository = "https://github.com/ifeanyi-ugwu/winston_rs"
authors = ["ifeanyi ugwu"]
keywords = ["winston", "logger", "logging"]
categories = ["development-tools::debugging"]


[dependencies]
async-trait = "0.1.83"
chrono = "0.4.38"
crossbeam-channel = "0.5.13"
futures = "0.3.30"
lazy_static = "1.5.0"
logform = "0.1.4"
once_cell = "1.19.0"
parking_lot = "0.12.3"
scoped_threadpool = "0.1.9"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
tokio = { version = "1.40.0", features = ["full"] }
winston_transport = { version = "0.1.2" }

[dev-dependencies]
criterion = "0.5.1"
tokio-test = "0.4.4"


[[bench]]
name = "logger_benchmark"
harness = false

[profile.bench]
debug = true

[[test]]
name = "logger_v2"
path = "tests/logger_v2/common_usage.rs"

[[test]]
name = "logger_v3"
path = "tests/logger_v3/common_usage.rs"
