[package]
name = "winston"
version = "0.1.0"
edition = "2021"
description = ""
license = "MIT"
documentation = "https://docs.rs/winston"
repository = "https://github.com/ifeanyi-ugwu/winston_rs"
authors = ["ifeanyi ugwu"]


[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
